package com.slc.assistivetouch.model.kernel;

public enum HwKeyTrigger {
    BIXBY_SINGLETAP,
    BIXBY_LONGPRESS,
    BIXBY_DOUBLETAP,
    HOME_LONGPRESS,
    BACK_SINGLETAP,
    BACK_LONGPRESS,
    BACK_DOUBLETAP,
    APP_SWITCH_SINGLETAP,
    APP_SWITCH_LONGPRESS,
    APP_SWITCH_DOUBLETAP,
    MENU_SINGLETAP,
    MENU_LONGPRESS,
    MENU_DOUBLETAP,
    CUSTOM_SINGLETAP,
    CUSTOM_LONGPRESS,
    CUSTOM_DOUBLETAP
}
